# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.


# configuration for release branches.
-
  branches:
    only:
      - /release.*/
  
  version: 1.0.0.{build}
  services: mssql2014
  nuget:
    project_feed: true
  before_build:
  - ps: >-
      $versionToUse = $env:APPVEYOR_BUILD_VERSION

      .\tools\SetVersion.ps1 $versionToUse Alpha
      
      nuget restore
  build:
    publish_nuget: true
    verbosity: minimal
  before_test:
  - ps: >-
      .\tools\CreateSqlDatabase.ps1 'LOCALHOST\SQL2014' 'IdentityNhibernate'

      .\tools\ReplaceFile.ps1 'tests\Dematt.Airy.Tests.Identity\hibernate.cfg.mssql.appveyor.xml' 'tests\Dematt.Airy.Tests.Identity\hibernate.cfg.mssql.xml'


# configuration for all other branches (all but the release branches).
-
  branches:
    except:
      - /release.*/
  
  version: 1.0.0.{build}
  services: mssql2014  
#  assembly_info:
#    patch: true
#    file: '**\AssemblyInfo.*'
#    assembly_version: '{version}'
#    assembly_file_version: '{version}'
#    assembly_informational_version: '{version}'
  before_build:
  - ps: >-
      $versionToUse = $env:APPVEYOR_BUILD_VERSION

      .\tools\SetVersion.ps1 $versionToUse Alpha
      
      nuget restore
  build:
    verbosity: minimal
  before_test:
  - ps: >-
      .\tools\CreateSqlDatabase.ps1 'LOCALHOST\SQL2014' 'IdentityNhibernate'

      .\tools\ReplaceFile.ps1 'tests\Dematt.Airy.Tests.Identity\hibernate.cfg.mssql.appveyor.xml' 'tests\Dematt.Airy.Tests.Identity\hibernate.cfg.mssql.xml'
